Read("CLP_core.g");;
Read("pairs_bigm.g");;

DescribeCode := function( lid, iid, mm, Aidx, Bidx, label )
    local pr, P, G, H, N, C, Ael, Bel, Aorders, Borders, i, gens, code, K, wts;
    pr := First( PAIRS, p -> p.l = lid and p.i = iid and p.m = mm );
    if pr = fail then Print("pair not found\n"); return; fi;
    P := LoadPair( pr );  PrepareActions( P );
    G := P.G;  H := P.H;  N := P.N;  C := P.core;

    Print( "\n================ ", label, " ================\n" );
    Print( "G  = SmallGroup(", lid, ",", iid, ")\n" );
    Print( "     StructureDescription: ", StructureDescription( G ), "\n" );
    Print( "     |G| = ", Size(G), ",  IsAbelian = ", IsAbelian(G),
           ",  IsNilpotent = ", IsNilpotent(G),
           ",  IsSolvable = ", IsSolvable(G), "\n" );
    Print( "     exponent = ", Exponent(G),
           ",  derived length = ", DerivedLength(G),
           ",  nr conj classes = ", NrConjugacyClasses(G), "\n" );
    Print( "     abelian invariants of G/G' = ", AbelianInvariants(G), "\n" );
    Print( "     IsDirectProduct-decomposable: ",
           Length( DirectFactorsOfGroup( G ) ), " factors -> ",
           List( DirectFactorsOfGroup(G), StructureDescription ), "\n" );

    Print( "H  = ", StructureDescription( H ), ",  |H| = ", Size(H), "\n" );
    Print( "     generators of H (as perms on G/H): ",
           List( GeneratorsOfGroup(H), g -> Order(g) ), " (orders)\n" );
    Print( "     IsNormal(G,H) = ", IsNormal(G,H), "\n" );
    Print( "N  = N_G(H) = ", StructureDescription( N ), ",  |N| = ", Size(N), "\n" );
    Print( "Core_G(H) = ", StructureDescription( C ), ",  |Core| = ", Size(C), "\n" );
    Print( "m = [G:H] = ", Index(G,H),
           ",  r = [G:N] = ", Index(G,N),
           ",  lift = [N:H] = ", Index(N,H),
           ",  stab = [H:Core] = ", Index(H,C), "\n" );
    Print( "|Im L| = |G/Core| = ", Size(G)/Size(C),
           ",  |Im R| = |N/H| = ", Index(N,H), "\n" );

    Ael := List( Aidx, row -> List( row, e -> List( e, k -> P.Areps[k] ) ) );
    Bel := List( Bidx, row -> List( row, e -> List( e, k -> P.Lreps[k] ) ) );
    Print( "\n-- group algebra elements --\n" );
    Print( "a (in F2[G], acting via L on G/H):\n" );
    for i in [1..Length(Ael)] do Print( "   ", Ael[i], "\n" ); od;
    Print( "   orders of a-terms: ",
           List( Ael, row -> List( row, e -> List( e, Order ) ) ), "\n" );
    Print( "   subgroup generated by a-terms: ",
           StructureDescription( Subgroup( G, Flat( Ael ) ) ),
           "  (index in G = ", Index( G, Subgroup( G, Flat(Ael) ) ), ")\n" );
    Print( "b (in F2[N_G(H)], acting via R on G/H):\n" );
    for i in [1..Length(Bel)] do Print( "   ", Bel[i], "\n" ); od;
    Print( "   orders of b-terms: ",
           List( Bel, row -> List( row, e -> List( e, Order ) ) ), "\n" );
    Print( "   subgroup generated by b-terms: ",
           StructureDescription( Subgroup( N, Flat( Bel ) ) ),
           "  (index in N = ", Index( N, Subgroup( N, Flat(Bel) ) ), ")\n" );

    Print( "\n-- ATB-style index table (indices into transversals, identity first) --\n" );
    Print( "   a = ", Aidx, "\n" );
    Print( "   b = ", Bidx, "\n" );
    Print( "   (l, m, s) = (", lid, ", ", iid, ", ", Size(C), ")\n" );

    code := CLP_Build( P, Aidx, Bidx, [1,1], [2,2] );
    K := code.N - RankMat(code.HX) - RankMat(code.HZ);
    wts := CodeWeights( code.HX, code.HZ );
    Print( "\n-- rebuilt code check --\n" );
    Print( "   n = ", code.N, ",  k = ", K, ",  w = ", wts.wmax,
           ",  HX rows = ", Length(code.HX), ",  CSS ok = ",
           IsZero( code.HX * TransposedMat( code.HZ ) ), "\n" );
end;;

DescribeCode( 270, 25, 90,
  [ [ [ 1, 122, 154 ] ] ],
  [ [ [ 1, 41 ], [ 1, 12 ] ], [ [ 1, 39 ], [ 24 ] ] ],
  "G1  [[360,16,<=22]]  w=7" );
QUIT;
